# Generated by Django 4.1.4 on 2022-12-06 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=30)),
                ('product_Price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_Name', models.CharField(max_length=50)),
                ('shop_Address', models.CharField(max_length=50)),
                ('shop_City', models.CharField(max_length=25)),
                ('shop_Longitude', models.CharField(max_length=25)),
                ('shop_Latitude', models.CharField(max_length=25)),
                ('shop_ContactNumber', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiANS.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiANS.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiANS.manufacturer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiANS.product')),
            ],
        ),
    ]
