# Generated by Django 4.0.4 on 2022-12-21 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiANS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Long', models.CharField(max_length=25)),
                ('user_Lat', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiANS.customuser')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DiANS.shop')),
            ],
        ),
    ]
