# Generated by Django 4.0.4 on 2022-12-21 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DiANS', '0002_customuser_customusershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='customUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DiANS.customuser'),
        ),
    ]
