# Generated by Django 4.0.4 on 2022-12-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DiANS', '0004_shop_shopuserdistance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusershop',
            name='custom_User',
        ),
        migrations.RemoveField(
            model_name='customusershop',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='ShopUserDistance',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='customUser',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='CustomUserShop',
        ),
    ]
